### ISSUE TITLE
Support for serializing

### ISSUE THREAD

**Issue by pjattke** [TeskaLabs/cysimdjson#15]
Hi! 
Does cysimdjson not support dumping/serializing a loaded JSON? I want to extract certain parts and then write them back to disk.

Thank you,
Patrick

**Comment by ateska** [comment]
Hi Patrick,

This is indeed interesting ... but since cysimdjson is "just" a binding to SIMDJSON, the design philosophy is to offer that C++ API of SIMDJSON offers. And that is parsing. Also the idea of read-only dictionary-like (or list-like) objects as the output of the JSON parser makes a lot of sense e.g. from perspective of functional programming (see single static assignment).

On the other hand, your request makes sense from the practical perspective.
Maybe https://github.com/lemire can comment if there are such plans in SIMDJSON.

Br,
Ales

**Comment by pjattke** [comment]
Hi @ateska 
Thanks for coming back to my question. I was hoping that I can replace [nlohmann/json](https://github.com/nlohmann/json) with cysmindjson but it seems like serialization is not a feature coming soon to cysimdjson, see [this issue](https://github.com/simdjson/simdjson/issues/1327).

Best regards,
Patrick
