### ISSUE TITLE
load to dict is slower than ujson

### ISSUE THREAD

**Issue by mjTree** [TeskaLabs/cysimdjson#23]
A big json_file convert python dict, use simdjson.Parser()  Object.as_dict().It‘s load speed is slower than ujson.

* python ujson loads             1.43 EPS (  6.30)    67.02 MB/s
* pysimdjson parse               1.42 EPS (  6.36)    66.36 MB/s
* python json loads              1.19 EPS (  7.57)    55.76 MB/s

**Comment by ateska** [comment]
SIMDJSON / cysimdjson leverages the fact that you don't covert the whole JSON into a Python dict. Because that's what is slow (relatively) - the construction of Python objects from JSON.

So you finding is correct; however that's not the way how you squeeze the performance out of the SIMDJSON in Python.
